# Generated by Django 3.1.2 on 2020-12-14 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=20)),
                ('date_de_naissance', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('specialitee', models.CharField(choices=[('L’immunologie', 'L’immunologie'), ('L’anesthésiologie', 'L’anesthésiologie'), ('L’andrologie', 'L’andrologie'), ('La cardiologie', 'La cardiologie'), ('La chirurgie cardiaque', 'La chirurgie cardiaque'), ('La chirurgie esthétique, plastique et reconstructive', 'La chirurgie esthétique, plastique et reconstructive'), ('La chirurgie générale', 'La chirurgie générale'), ('La chirurgie maxillo-faciale', 'La chirurgie maxillo-faciale'), ('La chirurgie pédiatrique', 'La chirurgie pédiatrique'), ('La chirurgie thoracique', 'La chirurgie thoracique'), ('La chirurgie vasculaire', 'La chirurgie vasculaire'), ('La neurochirurgie', 'La neurochirurgie'), ('La dermatologie', 'La dermatologie'), ('L’endocrinologie', 'L’endocrinologie'), ('La gastro-entérologie', 'La gastro-entérologie'), ('La gériatrie', 'La gériatrie'), ('La gynécologie', 'La gynécologie'), ('L’hématologie', 'L’hématologie'), ('L’hépatologie', 'L’hépatologie'), ('L’infectiologie', 'L’infectiologie'), ('La néonatologie', 'La néonatologie'), ('La néphrologie', 'La néphrologie'), ('La neurologie', 'La neurologie'), ('L’odontologie', 'L’odontologie'), ('L’oncologie', 'L’oncologie'), ('L’obstétrique', 'L’obstétrique'), ('L’ophtalmologie', 'L’ophtalmologie'), ('L’orthopédie', 'L’orthopédie'), ('L’Oto-rhino-laryngologie', 'L’Oto-rhino-laryngologie'), ('La pédiatrie', 'La pédiatrie'), ('La pneumologie', 'La pneumologie'), ('La psychiatrie', 'La psychiatrie'), ('La radiologie', 'La radiologie'), ('La radiothérapie', 'La radiothérapie'), ('La rhumatologie', 'La rhumatologie'), ('L’urologie', 'L’urologie')], max_length=70)),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('numero', models.CharField(max_length=70)),
                ('parcours', models.TextField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('CIN', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='salle_dattente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_case', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medecin')),
                ('malade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionniste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('CIN', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ppresent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.BooleanField()),
                ('temps_de_passage', models.DateTimeField()),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.salle_dattente')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='media')),
                ('titre', models.CharField(max_length=30)),
                ('Patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
