# Generated by Django 3.1.2 on 2020-12-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
